### ISSUE TITLE
Issue pls help

### ISSUE THREAD

**Issue by doggydoo123poo** [nur-zaman/valorantGPT#3]
Traceback (most recent call last):
  File "C:\Users\bobby\Desktop\valorantGPT-master\run_free.py", line 107, in <module>
    loop.run_until_complete(recconect_to_websocket())
  File "C:\Users\bobby\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\bobby\Desktop\valorantGPT-master\run_free.py", line 41, in recconect_to_websocket
    h = handle(response, endpoint)
  File "C:\Users\bobby\Desktop\valorantGPT-master\run_free.py", line 85, in handle
    response = use_deepai(content_prompt)
  File "C:\Users\bobby\Desktop\valorantGPT-master\run_free.py", line 55, in use_deepai
    for data in deepai.Completion.create(prompt=prompt):
  File "C:\Users\bobby\Desktop\valorantGPT-master\deepai\__init__.py", line 40, in create
    r.raise_for_status()
  File "C:\Users\bobby\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.deepai.org/chat_response
i get this error when someone sends a message

**Comment by nur-zaman** [comment]
This should be fixed with #4 . It would be best to redownload the repo and install the requirements again. Free version will take a bit time to start. Other than that if you face any more problems please create another issue.
